- pyxis/create_container_image.py
- pyxis/pyxis.py
- pyxis/test_create_container_image.py
- pyxis/test_pyxis.py
This commit adds a reworked version of the create-container-image script from the openshift ecosystem team to enable pushing container image metadata to pyxis.
> feat(HACBS-1259): add python script to upload data to pyxis

- .github/workflows/dockerfile_push.yaml
If the contents of this repo change, the image should be rebuilt so that there is an image available with the updated repo changes. It should not only be built on Dockerfile changes.
> fix: rebuild image for any change to the repo

- pyxis/create_container_image.py
After the post is done to pyxis, execute a get to make sure the image metadata was successfully added. This also has the added benefit of the containerImageID being printed out in all scenarios.
> fix(HACBS-1261): ensure pyxis image was successfully pushed

- copy-application.sh
The annotation got updated recently by the build service and
this PR satisfies the [new changes](https://github.com/redhat-appstudio/build-service/pull/103)
to make the service forward/backward compatible.
Signed-off-by: Happy <hbhati@redhat.com>
> fix(HACBS-1676): replace cleanup annotation

- pyxis/create_container_image
This commit reworks the logic of how the container image ID is logged in all instances. It reduces the calls to the api endpoint by parsing the returned data of the pyxis.post.
> refactor(HACBS-1261): log container image ID on pyxis post

- .github/workflows/build_and_push_image.yaml
There were some warnings, mainly that the action
versions we were using were using Node.js 12 which is now deprecated.
I also renamed the workflow to more accurately reflect what it's doing.
Also, I'm adding the latest tag for the image. It's nice to have since it's the default when pulling the image without specifying a tag.
Signed-off-by: Martin Malina <mmalina@redhat.com>
> fix: update github workflow to remove warnings

- pyxis/create_container_image
- pyxis/pyxis.py
There were a couple of issues:
- An unused import
- A wrong type used for logging level - it's set by constants which are int
- f-strings without any placeholders
We should really have linters run as part of a PR workflow here. I created a story for it: https://issues.redhat.com/browse/HACBS-1772
Signed-off-by: Martin Malina <mmalina@redhat.com>
> fix: fix linting errors

- setup-quay-push-secret.sh
Signed-off-by: Scott Hebert <shebert@redhat.com>
% ./setup-quay-push-secret.sh
```
Please enter the target workspace: [managed-release-team-tenant] temp4
Please enter the service account name: [release-service-account] 
Please enter the quay repo URL: [https://quay.io/repository/hacbs-release-tests/shebert-dc-metrocmap] 
Please enter your quay robot username: [] scoheb
Please enter your quay robot token: [] 
Going to create SPIAccessTokenBinding in temp4
spiaccesstokenbinding.appstudio.redhat.com/binding-dockerconfigjson-176186 created
Binding created
Waiting for AwaitingTokenData phase
spiaccesstokenbinding.appstudio.redhat.com/binding-dockerconfigjson-176186 condition met
Upload url: https://spi-oauth-spi-system.apps.scott-test-1717.clusters.stonesoupengineering.com/token/temp4/generated …
```
> chore(HACBS-1717) New script to setup quay secret

- pyxis/pyxis.py
The way it was set up, LOGGER calls in pyxis/create_container_image would actually not print anything to stdout. Now it works.
> fix: set up logging correctly

- Dockerfile
cosign is needed for sbom download in our tekton tasks. Previously, we thought we could use the cosign container directly in a tekton step, but because we'll have multiple components/images, we will need the binary to call it repeatedly.
> feat(HACBS-1551): install cosign binary

- pyxis/test_create_container_image.py
I used a line length of 88 for checking (flake8 default is 79, but black defaults to 88 and we are also using black).
> fix(HACBS-1772): fix current flake8 errors

- .flake8
- .github/workflows/lint.yaml
- pyproject.toml
- pyxis/pyxis.py
- pyxis/test_pyxis.py
This PR has two commits. One changes the max line length for black and flake8 in this repo to be 95 (and adds config files doing that). The second adds a github action to enforce flake8 formatting
> Add flake8 action and set max line length to 95

- Dockerfile
- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
This PR includes renaming `create_container_image` back to have its .py suffix. This is because the imports don't work properly without it. There are workarounds (see https://stackoverflow.com/questions/2601047/import-a-python-module-without-the-py-extension) but I think it would be nice to just put the suffix back. Open to discussion on it
> fix(HACBS-1803): fix current pytest errors

- Dockerfile
`COPY` uses the current directory as its src, unlike `cp`
> fix: use RUN cp instead of COPY in dockerfile

- Dockerfile
- README.md
- pyxis/test_create_container_image.py
The release-utils repo was moved from hacbs-release/release-utils to redhat-appstudio/release-service-utils. This commit changes the references in this repo.
> chore(HACBS-1614): release-utils repo rename

- Dockerfile
- pyxis/test_upload_sbom.py
- pyxis/upload_sbom.py
This script will push sbom data to Pyxis.
The script is ready for review. Unit tests will be added once first iteration of review is done to avoid wasting time in case significant refactoring comes out of the review.
For input, you'll need a Pyxis image id and an sbom. For how to get an sbom for an image url, see here: https://github.com/hacbs-release/release-bundles/pull/92
You'll need cosign:
- How to install: https://docs.sigstore.dev/cosign/installation/
- And then run something like: `cosign download sbom --output-file my-sbom.json $IMAGE_URL`
Then run the script, e.g.:
```
$ ./pyxis/upload_sbom.py --pyxis-graphql-api https://graphql.pyxis.qa.engineering.redhat.com/graphql/ --image-id 64020cafb94be12a048de276 --sbom-path ~/tmp/sbom/sbom-cyclonedx.json
```
> feat(HACBS-1552): add upload_sbom script

- pyxis/pyxis.py
- pyxis/test_pyxis.py
- pyxis/test_upload_sbom.py
- pyxis/upload_sbom.py
image_id was None if taken from sbom filename.
It was calculated properly, but then the wrong
variable was used.
Check for existing content_manifest and
content_manifest_components in image was wrong.
The old code worked when REST api was used, but
since I switched to GraphQL, the properties will
always exist and be None if no objects are found.
Also, split out graphql queries into a new function. This includes improved error handling.
Before this change, in some testing I was
getting unhelpful error messages when the request
failed on a lower level (e.g. wrong query parameter).
> fix(HACBS-1553): bugs in upload sbom script

- pyxis/test_upload_sbom.py
- pyxis/upload_sbom.py
The image objects in Pyxis will no longer contain
embedded content_manifest_components objects in them. We were relying on this, so we have to use
edges instead.
> refactor(HACBS-2375): adjust sbom script for pyxis changes

- Dockerfile
Red Hat IT Root CA is unreachable from actions so this PR removes the fetching
of it to unblock image builds until we find a permanent solution.
> fix: remove fetching of unreachable CA

- pyxis/create_container_image.py
- pyxis/pyxis.py
- pyxis/test_create_container_image.py
- pyxis/test_pyxis.py
- pyxis/test_upload_sbom.py
- pyxis/upload_sbom.py
This PR adds two improvements:
1. Print pyxis trace_id on graphql failure - this will help with debugging if the Pyxis request fails
2. Add retry option for upload_sbom script - this option will be used in the Tekton task and it will improve the reliability of the pipeline
> feat(HACBS-2271): improve reliability of upload_sbom script

- pyxis/upload_sbom.py
This is based on feedback in
https://github.com/redhat-appstudio/release-service-utils/pull/46 and by accident it was left out from that PR.
> refactor(HACBS-2271): improve help message for retry option

- utils/git-functions
Use git shallow clone to save disk space and clone time.
> chore: use git shallow clone

- .github/gitlint/contrib_format_conventional_commits.py
- .gitlint
Adds linting for commit messages including "revert" prefix support
> feat(HACBS-2506): add linting for commit messages

- utils/gitlab-functions
This PR adds the new parameters `--upstream-repo` and `--target-branch` to the `gitlab_create_mr` function.
Signed-off-by: Leandro Mendes <lmendes@redhat.com>
> feat(HACBS-2590): adds new parameters to gitlab_create_mr

- utils/git-functions
- utils/gitlab-functions
This PR adds the git_rebase function to git-functions so tasks that uses it can rebase the local (a fork, in case of file-updates) with the upstream with a given branch.
Also some small code adjusts.
> fix: fork should be rebased with upstream branch before MR

- utils/internal-request
This PR fixes the script to make it check if the InternalRequest
has Succeeded or not and exit accordingly.
Signed-off-by: Leandro Mendes <lmendes@redhat.com>
> chore(HACBS-2593): internal-request script should fail on IR failure

- Dockerfile
- requirements.txt
- templates/advisory.yaml.jinja
- utils/apply_template.py
- utils/test_apply_template.py
As part of RHTAPREL-392, we need to create advisories. The easiest way to do this is from a template using ansible, so this commit adds ansible and a template to the repo.
> feat(RHTAPREL-392): add jinja2 and templating to the image

- Dockerfile
- pin base image in Dockerfile
- specify labels that we should not be overriding
- upgrade OPM version due to
https://redhat-internal.slack.com/archives/C3VS0LV41/p1697051133176919
> chore(RHTAPREL-435): pin base image and update labels

- utils/merge-json
```
[jbieren@jbieren utils]$ echo $json1
{"data":{"foo":"bar"}}
[jbieren@jbieren utils]$ echo $json2
{"data":{"one":"two"}}
[jbieren@jbieren utils]$ echo $json3
{"data":{"one":"three"}}
[jbieren@jbieren utils]$ ./merge-json $json1 $json2
{"data":{"foo":"bar","one":"two"}}
[jbieren@jbieren utils]$ ./merge-json $json2 $json3
{"data":{"one":"three"}}
```
without the fix, it was like this
```
[jbieren@jbieren utils]$ ./merge-json $json1 $json2
{"data":{"one":"two"}}
```
> fix: merge-json doesn't merge properly

- utils/get-resource
This commit changes the behavior of the get-resource util to return {} instead of the empty string if a jsonpath is passed and the key is not found.
> feat: get-resource returns {} if json key not found

- Dockerfile
> chore(deps): update to latest ubi8 base image

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
The field is needed for image grading.
We did set this field in the past, but it was accidentally removed when fixing RHTAPBUGS-756 .
> fix(RHTAPBUGS-927): add image_id back when creating image in Pyxis

- utils/apply_template.py
Change the apply_template.py util to keep the undefined variables in the template instead of removing them.
> feat(RHTAPREL-643): keep undefined variables in templates

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
Based on discussion with rbean and jvulgan in Slack, we should actually create two items in ContainerImage.repositories for images pushed to registry.redhat.io. The first one will be the same as for other pushes. The second one will have the registry and repository values converted (see the Python script documentation for more details).
The quay.io entry will be used for pulling the image for grading of the image by Clair.
> feat(RHTAPREL-618): create two repos when pushing to registry.redhat.io

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
The tag cli argument was renamed to tags and now it supports multiple tags using a single string with tags separated by space.
> feat(RHTAPBUGS-946): support multiple tags in create_pyxis_image

- .tekton/release-service-utils-pull-request.yaml
- .tekton/release-service-utils-push.yaml
- this is an attempt to dogfood a new feature in RHTAP - source container builds.
- thanks to this PR, it has uncovered the following EC issue: https://redhat.enterprise.slack.com/archives/C031J4KBFME/p1699019703358069?thread_ts=1699019703.358069&cid=C031J4KBFME
> chore: enable source container builds

- pyxis/pyxis.py
- pyxis/test_pyxis.py
In my testing, when running this script against qa Pyxis with an sbom that has 113 components, this will yield around 27 % of script runtime reduction.
Note that I'm also working on batching of the component creation in Pyxis which will bring even more performance increase, but that will be another PR.
> refactor(RHTAPBUGS-919): reuse session in pyxis api calls

- .flake8
- pyxis/pyxis.py
- pyxis/test_pyxis.py
- pyxis/test_upload_sbom.py
- pyxis/upload_sbom.py
- templates/create_content_manifest_components.graphql.jinja
By creating sbom components in Pyxis in batches
of 5, the overall script runtime is reduced by around
47 % in my testing with an sbom with 113 components.
The batch size is configurable, but currently set to 5.
Note that this is a follow up of https://github.com/redhat-appstudio/release-service-utils/pull/91 which is merged now.
> refactor(RHTAPBUGS-919): create components in batches

- LICENSE
License was missing in this repo. Add Apache 2 license. This was brought up by mbasti, thanks!
> chore: add apache 2 license to repo

- utils/internal-request
- utils/wait-for-ir
The new wait-for-ir script will wait for one or more InternalRequests to complete. The IR(s) to wait for can either be specified by a name or using a label selector.
The internal-request script was modified to use this new script if used in sync mode (-s).
Note that this is needed for https://github.com/redhat-appstudio/release-service-catalog/pull/319 and is tested there.
> feat(RHTAPBUGS-959): add wait-for-ir script to enable parallel runs

- utils/wait-for-ir
This commit refactors the wait-for-ir script to take a list of labels instead of accepting an identifier value.
> refactor: wait-for-ir accepts labels

- utils/translate-delivery-repo
This commit adds the translate-delivery-repo to translate quay.io/redhat-prod/product----repo into registry.redhat.io/product/repo and quay.io/redhat-pending/product----repo into
registry.stage.redhat.io/product/repo. This translation will need to be done in multiple places, so it should be stored as a utility in this image instead of repeating the logic in multiple locations.
> feat(RHTAPREL-816): add translate-delivery-repo utility

- utils/translate-delivery-repo
Some tests call the translation even when they aren't using a quay.io/redhat-[prod,pending] repo. As the old behavior did not fail in these cases, this commit changes translate-delivery-repo to also not fail in these scenarios.
> fix(RHTAPREL-816): don't fail translate-delivery-repo

- utils/translate-delivery-repo
Index images use quay.io/redhat/ and need to be translated to registry.redhat.io. This commit updates the translate-delivery-repo utility to handle this case.
> refactor(RHTAPREL-816): translate-delivery-repo supports index images

- pyxis/test_upload_sbom.py
- pyxis/upload_sbom.py
In the upload_sbom script, when we initially start processing an image, there will be no associated content_manifest yet. Previously, the content_manifest_components edge would still return an empty array in its data field and we relied on it.
But the correct behavior is to return an error for the edge instead and the Pyxis team deployed this change which broke our script. They reverted the change until we address it which is happening with this change.
This adds a check so that when there is no content_manifest, we don't even check the components.
More error handling will be added later.
> fix(RHTAPREL-857): handle case when there is no content_manifest yet

- templates/advisory.yaml.jinja
This field will initially have the same value
as ship_date. The intention is that it will be updated manually if the advisory is updated in the gitlab repo in the future.
> feat(RHTAPREL-799): add updated_date to advisory template

- Dockerfile
We need to add the `name` and `com.redhat.component` labels to avoid an EC violation.
> chore: add name and com.redhat.component labels

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
The pyxis schema can only accept an array here, not None, however skopeo can return null/None. Here, if the value is falsy, then use an empty array rather than the falsy value.
> fix: handle null Env from skopeo

- utils/translate-delivery-repo
This commit updates the translate-delivery-repo to return a JSON string that has both the registry.redhat.io repo and the
registry.access.redhat.com repo (and their stage versions).
> feat(RHTAPREL-863): return both redhat registries with util

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
- utils/get-image-architectures
We need both when creating a multi-arch image. Both manifest_schema2_digest and manifest_list_digest should be supplied.
> fix: accept both index and manifest digests when creating pyxis records

- utils/get-image-architectures
The tekton tasks would all need to change the json to compact if we do not do it here.
> fix(RELEASE-1): get-image-architectures uses compact json

- .github/CODEOWNERS
- The team name changed after migration to konflux-ci. 
The CODEOWNER requires an update to match the new name.
> fix: update codeowner

- pyxis/cleanup_tags
- pyxis/cleanup_tags.py
- pyxis/test_cleanup_tags.py
This script will take a Pyxis Container Image ID as input and it will remove all its tags from all previous images that use the Red Hat registry and the same repository and architecture.
> fix(KFLUXBUGS-1294): add cleanup_tags script for cleaning up tags

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
It turns out using the main digest was wrong and as a result clair was failing to grade our images.
> fix(RELEASE-998): use arch specific digest for image_id in Pyxis

- Dockerfile
- utils/get-image-architectures
I'd like to use it to run `oras resolve` to get the top-level digest of OCI artifacts that are not images.
> chore: include oras in utils image

- pyxis/test_upload_sbom.py
- pyxis/upload_sbom.py
It seems that bundles could no contain the components key in the sbom. This causes the upload_sbom script to fail whenever the components are loaded.
> fix(RELEASE-1000): prevent failure if no components key found

- Dockerfile
This commit adds the python3-rpm, krb5-libs, and krb5-devel packages to the image as required by the script that will be used for RELEASE-971 to push content with pub tools pulp push.
> feat(RELEASE-971): add required packages

- .github/workflows/python.yaml
- Dockerfile
- pubtools-pulp-wrapper/pulp_push_wrapper
- pubtools-pulp-wrapper/pulp_push_wrapper.py
- pubtools-pulp-wrapper/test_pulp_push_wrapper.py
- requirements.txt
This change adds and new script stored in dedicated directory.
This script will be used for pushing content for RELEASE-971.
Necessary updates to Dockerfile and requirements.txt were done
as well to allow the same execution conventions for new script
as there are already for `pyxis` scripts.
Signed-off-by: Robert Bikar <rbikar@redhat.com>
> feat(RHELDST-24850): add pubtools-pulp-push wrapper script

- Dockerfile
- requirements.txt
pubtools-content-gateway was upgraded - https://github.com/release-engineering/pubtools-content-gateway/commit/82d7e652791e000616d6c8a6071d721a3019c588
This commit aims to install library directly from [pypi](https://pypi.org/project/pubtools-content-gateway/) instead of cloning the repo.
JIRA: RELEASE-1025
> fix(RELEASE-1025): stop cloning the repo, install library from pypi

- utils/internal-request
This commit modifies the internal-request script in the utils directory to accept timeout values for the pipeline, task, and finally blocks that will be passed to tekton when created the pipelineRun.
> feat(RELEASE-971): add plr timeouts to InternalRequests

- pyxis/test_upload_rpm_manifest.py
- pyxis/upload_rpm_manifest.py
Without these fields the rpms do not get displayed in Red Hat Catalog. Unfortunately, currently we cannot get the real summary anywhere, so for now at least put the nvra or name value in that field - better to display something than nothing.
> fix(RELEASE-980): populate nvra and summary in Pyxis RpmsItems

- pyxis/test_upload_rpm_manifest.py
- pyxis/upload_rpm_manifest.py
This commit modifies the upload_container_rpm_manifest_with_retry function to retry if the exception is an HTTPError with code 504. Other HTTPErrors will fail immediately, as is currently the case for all HTTPErrors.
> fix(KFLUXBUGS-1480): retry upload_container_rpm_manifest on HTTPErrors

- pyxis/cleanup_tags.py
- pyxis/test_cleanup_tags.py
Before this fix, if there were no tags in the repository of the ContainerImage object, the script would fail on: TypeError: 'NoneType' object is not iterable
That's because in the returned image object,
tags would be null/None instead of an empty list.
Now we handle this use case.
> fix: handle empty tags in cleanup_tags script

- Dockerfile
We're trying to use release-service-utils in our release pipeline, which needs a more recent cosign support due to some verification errors. The related PR in release-service-catalog is here: https://github.com/konflux-ci/release-service-catalog/pull/510
> fix(MMENG-4169): update cosign to 2.4.0

- .github/workflows/lint.yaml
- .github/workflows/python.yaml
There was a warning displayed along the workflow runs in Github: The following actions use a deprecated Node.js version and will be forced to run on node20:
actions/checkout@v3, actions/setup-python@v4
> chore: update checkout and python actions

- .gitlint
This commit modifies the gitlint configuration to ignore the max title length and max body line length rules for bot accounts. This should encompass both dependabot commits and red-hat-konflux-bot commits.
> fix: ignore gitlint checks for bots

- pubtools-pulp-wrapper/pulp_push_wrapper.py
By default, logging goes to stderr in Python. This will change it to go to stdout. That makes it in line with our other Python scripts and also, it will help with debugging when this script runs in the Tekton task, because we suppress stderr there (and only print it if the script fails).
Here's where the script is called from: https://github.com/hacbs-release/app-interface-deployments/blob/main/internal-services/catalog/pulp-push-disk-images-task.yaml#L246
> fix: pulp wrapper logging to print to stdout

- developer-portal-wrapper/developer_portal_wrapper.py
By default, logging goes to stderr in Python. This will change it to go to stdout. That makes it in line with our other Python scripts and also, it will help with debugging when this script runs in the Tekton task, because we suppress stderr there (and only print it if the script fails).
> fix(RELEASE-1108): logging should go to stdout

- pyxis/test_upload_rpm_manifest.py
- pyxis/upload_rpm_manifest.py
To fix KONFLUX-4175, we need to upload a gpg key id to pyxis.
The right way to do this is for the SBOM itself to contain the gpg key id. Our task here would simply copy it to pyxis.  However, to do that fully, we'll need to get a change into both syft and cachi2, which may take some time.
As a stopgap, this change inspects the "publisher" field of the sbom. If it is set to Red Hat, we'll publish the Red Hat release2 key id to pyxis.
You might ask, what if the rpms are not actually signed by Red Hat keys? We have a separate layer of protection against that in KONFLUX-3149, but the data about which rpms are signed by which keys will not be exposed by that work in the way that the release process can use here.
* https://issues.redhat.com/browse/KONFLUX-4292
* …
> fix(KONFLUX-4292): upload a fixed gpg key id to pyxis

- pyxis/test_upload_rpm_data.py
- pyxis/upload_rpm_data.py
We're looking for "Red Hat, Inc." in the publisher field to set a fixed gpg key (it's a temporary measure that will be removed later), but there was a typo
in the string, so it didn't work.
> fix(KONFLUX-4292): typo in rpm publisher field check

- .github/workflows/lint.yaml
Latest ubuntu does not allow system wide pip install. It can be overriden with `--break-system-packages`, but it's better to create a virtual env.
This first came up here: https://github.com/hacbs-release/app-interface-deployments/pull/198
> fix: gitlint installation

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
Notably, this needs to be populated by `oras` in the task that invokes this script, but the test suite here verifies that the script will not break if this is rolled out before that task is modified.
https://issues.redhat.com/browse/KONFLUX-4892
> feat(KONFLUX-4892): supply layer size information to pyxis

- sbom/create_product_sbom.py
- sbom/test_create_product_sbom.py
These guidelines are defined at:
https://redhatproductsecurity.github.io/security-data-guidelines/sbom/
Specific changes:
- Datetimes should always use UTC
- `documentNamespace` doesn't need to contain any product-specific information and serve only as an identifier (this information can be set in the `name` field")
- Data license should be `CC-BY-4.0`
- The `creators` field should note the Tool that is used to generate the SBOM. Also the SPDX 2.3 JSON schema requires the field to be called `creators` instead of `creator`: https://github.com/spdx/spdx-spec/blob/v2.3/schemas/spdx-schema.json
> Tweak product SBOM generator

- sbom/create_product_sbom.py
- sbom/test_create_product_sbom.py
The name format defined in the script is different from what is expected. This commit removes the underscore in the name and replace it with a space.
JIRA: ISV-5314
> Update product level SBOM name

- pyxis/test_upload_rpm_data.py
- pyxis/upload_rpm_data.py
We found that only syft SBOM entries contain the publisher field.
Here, extend the workaround logic to assume that every rpm in the redhat namespace bears the right key.
> fix(KONFLUX-4292): handle case where SBOM has no publisher

- templates/advisory.yaml.jinja
- utils/test_apply_template.py
This fixes a particular case with long urls which got split when over the 76 character limit. Those then got a space inserted in the middle of them because of the way markdown works when you split long strings.
The solution here is just to not wordwrap the advisory yaml output.
I figure, it is meant for machines anyways, not humans, so it doesn't matter if it has long lines.
> fix(TEAMNADO-7734): don't mangle long strings when generating advisories

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
- some products may release an image to 2 locations in the catalog.
- rhel9/buildah and ubi9/buildah for example.
- this PR extends the image_exists function with the repo name
> fix(KFLUXBUGS-1848): extend image_exists with repo

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
- we need to ensure we use the repo name in the form 'ubi9/buildah' given a passed name arg of 'quay.io/pending/ubi9----buildah'
> fix(KFLUXBUGS-1848): wrong name used in imageexist

- pyxis/create_container_image.py
- pyxis/pyxis.py
- pyxis/test_create_container_image.py
This adds a new behavior.
If asked to create an image associated with a repository, and the image does not exist at all - then create it, as before.
If the image does exist, but is not associated with the desired repository, then submit a PATCH request to update it, adding the desired repository.
This is related to https://github.com/konflux-ci/release-service-utils/pull/300 and KFLUXBUGS-1848.
> fix(KFLUXBUGS-1848): associate existing images with a new repository

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
In the event that an image does not have any gzipped layers, then no uncompressed layer information will be handed to this tool and it will pass on the None value to pyxis. That fails pyxis' input validation, blocking containerImage creation.
In this change, simply drop these values if they happen to be none.
> fix: handle none-type values more carefully

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
We're populating containerImage entities incorrectly.
I think this has no real effect, but if you look at one that we generate, the manifest_list_digest and manifest_schema2_digest are always the same, but they're not supposed to be. We currently incorrectly always set them to the value of the arch-specific image manifest, when the point is to provide both values, the multi-arch image index manifest as the manifest_list_digest and the arch-specific image manifest as the manifest_schema2_digest.
> fix: supply manifest list digest to pyxis

- sbom/test_update_component_sbom.py
- sbom/update_component_sbom.py
Previously the update-component-sbom script is only updating the component purl in the list of components. But in CycloneDX, there is also a component purl in the metadata.
> fix(ISV-5128): also update sbom metadata component purl

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
- pyxis/test_pyxis.py
This is a followup of what was done in #303
Most notably:
- rename the image_already_exists to find_image to reflect what it does - it used to return bool, now it returns the image if found.
- only get the image from Pyxis once - no need to get it a second time with the repository in the filter, we can just search through the repositories in the image that we got from the first request
- only include the repositories field in the patch payload
- for consistency, create the same two repo entries when adding a new repository like we do when creating a brand new image
It seems this mostly covers https://issues.redhat.com/browse/RELEASE-1285 as well - I just need to add tests for pyxis.patch.
> refactor: patching ContainerImage to add repositories

- utils/get-image-architectures
If skopeo inspect fails, the variable would be empty and then the jq query would return an empty string instead of null, so we would assume it's an oci artifact and run oras resolve.
If we were unable to fetch the image details with skopeo inspect we should just fail the script.
> fix(KFLUXBUGS-1846): fail get-image-architectures if skopeo failed

- sbom/test_update_component_sbom.py
- sbom/update_component_sbom.py
This commit sets a name field of the component image SBOM to image pullspec made of repository and image digest. The pullspec is parsed from image purl.
The name is originally set in the build phase but it refers to an internal Quay repository. In the release time we need to set it to a public repository name that is available to customer.
JIRA: ISV-5321
> feat(ISV-5321): update SPDX document name value

- pyxis/create_container_image.py
We do publish images to registry.access.redhat.com now.
> docs: update note about Red Hat registries

- Dockerfile
- pubtools-marketplacesvm-wrapper/marketplacesvm_push_wrapper
- pubtools-marketplacesvm-wrapper/marketplacesvm_push_wrapper.py
- pubtools-marketplacesvm-wrapper/test_marketplacesvm_push_wrapper.py
- requirements.txt
This commit introduces a wrapper for `pubtools-marketplacesvm` which aims to be eventually used to support VM images pushes on various cloudmarketplaces (such as AWS and Azure).
With this wrapper it will be possible to easily integrate the tooling into Tekton CI using the Cloud Staged structure as input.
Refers to SPSTRAT-464
> Add wrapper for pubtools-marketplacesvm

- developer-portal-wrapper/developer_portal_wrapper.py
- Change name of CGW_TOKEN to CGW_PASSWORD
- This is actually a token, no pw, but the pubtools library expects this environment variable name
- No longer pass token with command invocation
- This accompanies the following PR:
- https://github.com/hacbs-release/app-interface-deployments/pull/245
- Relevant PR to pubtools: https://github.com/release-engineering/pubtools-content-gateway/pull/38
> fix(KFLUXSPRT-794): pass content-gateway token as env var

- pubtools-marketplacesvm-wrapper/marketplacesvm_push_wrapper.py
- pubtools-marketplacesvm-wrapper/test_marketplacesvm_push_wrapper.py
This commit updates the regex patter for validating the staged directory path string.
> fix(marketplacesvm): path regex

- .tekton/release-service-utils-pull-request.yaml
- .tekton/release-service-utils-push.yaml
One of the images used in the build pipeline was deleted, so this commit switches us to a different sha of the task.
> fix: build pipeline task sha was removed

- Dockerfile
Add missing dependency `packaging` for `pubtools-marketplacesvm`
> fix(deps): adds packaging module on Dockerfile

- sbom/test_update_component_sbom.py
- sbom/update_component_sbom.py
Since this script won't use the advisory data anymore, the SBOM data can be simplified.
> feat: change image data field

- pyxis/create_container_image.py
- pyxis/test_create_container_image.py
Before this change there was no way to rerun a release pipeline with the intention of changing some tags - the create_container_image would detect that the image already exists in Pyxis and has the required repository defined and it would stop right there.
Now this scenario is supported - if the image already exists and it includes the required repository, we check if the tags are the same. If not, we update them to the desired list of tags.
> feat: implement updating of image tags

- templates/advisory.yaml.jinja
This commit adds severity to the advisory template so that we can start adding it to our advisories. It is in an if statement as only certain types of advisories should have it set.
> feat(RELEASE-1353): add severity to advisory template

- Dockerfile
- publish-to-cgw-wrapper/publish_to_cgw_wrapper
- publish-to-cgw-wrapper/publish_to_cgw_wrapper.py
- publish-to-cgw-wrapper/test_publish_to_cgw_integration.py
- publish-to-cgw-wrapper/test_publish_to_cgw_wrapper.py
This script automates pushing files to the CGW:
- Reads metadata and processes files from the content directory.
- Checks if a file already exists in the product version based on the label, short URL, and download URL, skipping duplicates to avoid failure.
- Creates new files and returns their IDs upon success.
- Generates a JSON report summarising the number of files created, skipped, and the metadata used.
RELATES TO: https://github.com/konflux-ci/release-service-catalog/pull/781
> feat(RELEASE-1246): implement script to push files to CGW

- pyxis/test_upload_rpm_data.py
- pyxis/upload_rpm_data.py
The script was failing for a user when it tried to access qualifiers for a purl dict and there were none. I discussed this with the build team and they agreed that we should ignore such entries. In most cases this will be a duplicate package entry anyway. More details in Jira.
> fix(RELEASE-1455): ignore purls without qualifiers in spdx sboms

- sbom/create_product_sbom.py
- sbom/test_create_product_sbom.py
The relationship in the product-level SBOM was the wrong way around. I will update the image tags in release-service-catalog when this is merged.
> fix(ISV-5685): fix component-product relationship

- utils/get-image-architectures
If one of the skopeo or oras calls failed, the script would continue to run and provide incorrect/empty output.
By using `set -e`, it will fail immediately if one of the calls fails.
We could implement a retry here, but these failures are pretty rare and we also have retry enabled on task level, so that should be good enough for now.
> fix(KONFLUX-6580): use set -e in get-image-architectures

- pyxis/create_container_image.py
Sometimes an image can end up with no tags. That might happen if it only has floating tags and those were reused in another image and so the tags would be removed from this image.
A user encountered this recently and we also saw this in e2e.
Related support case: [KONFLUX-7267](https://issues.redhat.com/browse/KONFLUX-7267)
> fix: key error if Pyxis image repository has no tags

- pyxis/create_container_image.py
It turns out my previous fix did not work. The `tags` field is not missing, but it's None. This will ensure that in this case an empty list is used.
> fix: empty tags in create_container_image

- Dockerfile
The updated version supports docker.io.
> chore(RELEASE-1221): bump oras image to get select-oci-auth update

- utils/curl-with-retry
This new script will retry in case of code 429 - api rate limiting. It can be used as a drop in replacement for curl with a few caveats:
* -o/--output should not be specified - the response will always be printed to stdout
* --fail should not be specified. The script will always fail if curl ends up failing.
Is needed by https://github.com/konflux-ci/release-service-catalog/pull/866
> feat(RELEASE-1461): add curl-with-retry to handle Jira rate limiting

- Dockerfile
Pypi version of python3-qpid-proton doesn't provide SSL support for proton. Therefore rpm has to be installed instead
> Added python3-qpid-proton to enable SSL support

- Dockerfile
- requirements.txt
- sbom/README.md
- sbom/handlers/__init__.py
- sbom/handlers/spdx2.py
- sbom/logging.py
- sbom/sbomlib.py
- sbom/test_create_product_sbom.py
- sbom/test_sbomlib.py
- sbom/test_update_component_sbom.py
- sbom/testdata/single-component-multiarch/spdx/build_image_sbom.json
- sbom/testdata/single-component-multiarch/spdx/build_index_sbom.json
- sbom/testdata/single-component-multiarch/spdx/release_image_sbom.json
- sbom/testdata/single-component-multiarch/spdx/release_index_sbom.json
- sbom/testdata/single-component-single-arch/spdx/build_sbom.json
- sbom/testdata/single-component-single-arch/spdx/release_sbom.json
- sbom/update_component_sbom.py
In this PR, the component-level SBOM update process for SPDX-2.X is rewritten. While before we relied on data from non-SBOM related tasks, now we work with inputs that are defined better.
The only input required to update component-level SBOMs is now the mapped snapshot spec (exported by the `apply-mapping` task).
The snapshot is then parsed into a Python object that contains references to all images (with arch-specific images in the case of multiarch).
This object is then used to asynchronously download the SBOMs for all images and update them based on the snapshot being released.
> feat(ISV-5760): rework SBOM generation

- utils/internal-request
All catalog tasks have been refactored to use git resolvers now. So, we can drop support for the `-r <request>` field in the internal-request script.
This makes it so the script doesn't support cluster references anymore. If we want to do that in the future, we can using a new type of resolver, but still not just the taskRef name, as the current -r uses.
> refactor(RELEASE-1378): remove request support in internal-request

- sbom/handlers/__init__.py
- sbom/handlers/cyclonedx1.py
- sbom/handlers/spdx2.py
- sbom/sbomlib.py
- sbom/test_update_component_sbom.py
- sbom/testdata/single-component-single-arch/cdx/build_sbom.json
- sbom/update_component_sbom.py
This PR rewrites the CycloneDX SBOM update logic using the new API from sbomlib. We bump the version of all SBOMs to 1.6, so the `evidence.identity` field supports our tag use case (CycloneDX 1.X is forward-compatible).
**CycloneDX index image SBOMs are not supported**, because Konflux only generates index image SBOMs in the SPDX format.
> feat(ISV-5785): rewrite CycloneDX update logic

- templates/advisory.yaml.jinja
- utils/test_apply_template.py
- ensure additional jira field in data model for issues does not alter the advisory rendered format of issues.
- the goal is to allow other advisory keys makes use of additional jira fields like summary.
> feat(RELEASE-1569): allow other jira fields

- templates/advisory.yaml.jinja
- utils/test_apply_template.py
This PR aims to change the `synopsis` field from a single line to a multiple lines.
> feat(templates): change 'synopsis' to be multiline

- sbom/create_product_sbom.py
- sbom/logging.py
- sbom/test_create_product_sbom.py
By naming the file according to its contents in this script, we can simplify the Tekton task that uses it.
With the move to Atlas V2, the name is no longer used as an ID, so we can use a more human-readable name.
> feat: determine name for product SBOM in-script

- templates/advisory.yaml.jinja
- utils/test_apply_template.py
- a recent change removed all other fields except id and source
- the public field is added by the pipeline and is needed for rendering later in customer portal
> fix: re-add public field for issues

- utils/curl-with-retry
We got a report from a user showing that Jira
will return code 201 when closing an issue
and our script would consider it a failure.
Anything >= 200 and < 300 is a success.
Another potential issue could be 3xx codes,
but we don't expect those now and normally
you'd want to use -L to follow those
anyway. So we shouldn't have to worry about
that.
Slack thread: https://redhat-internal.slack.com/archives/C04PZ7H0VA8/p1748510448369709
> fix: successful http codes in curl-with-retry

- sbom/handlers/cyclonedx1.py
- sbom/sbomlib.py
- sbom/test_sbomlib.py
- sbom/update_component_sbom.py
The update_component_sboms script was silently failing on a cosign authorization issue. This PR fixes the cause of the silent failures and the auth issue itself.
Cosign was failing because the authentication file was not named "config.json" as expected.
> fix(ISV-5990): fix SBOM update failing silently

- utils/get-image-architectures
this PR adds the --skopeo-retries to the script
get-image-architectures to enable the skopeo
option --retry-times to use it.
> feat(RELEASE-1664): use --retry-times for skopeo inspect

- sbom/test_update_component_sbom.py
- sbom/update_component_sbom.py
If we do this in parallel and if a pullspec is listed in a snapshot twice, then the two routines collide, one fetching and the other writing the augmented sbom - resulting in malformed json.
> Put file locking around writes to sbom files

- utils/get-image-architectures
Not all non-image OCI artifacts have .artifactType != null.
For example, Helm artifacts don't include that field at all.
Extending the check for recognizing generic artifacts to also include
Helm charts.
> chore: identify helm chart artifacts

- templates/advisory.yaml.jinja
We are removing the field from the advisory yaml files. Instead, this field will be injected in the Gitlab CI pipeline before the UMB message is sent. This is already implemented in both staging and production advisory repos.
> feat(RELEASE-1570): stop populating updated_date in advisories

- .tekton/release-service-utils-pull-request.yaml
Since "./***".pathChanged()" can't work well  and  the task "check-if-e2e-irrelevant" was added to e2e pipeline, the PR is to remove file filering in tekton config file.
failed example: https://github.com/konflux-ci/release-service-utils/pull/493#issuecomment-3188562147
> fix: remove file filtering in tekton config file

- utils/get-image-architectures
Include artifact's config.mediaType in the output of get-image-architectures so it can later be used by apply-mapping.
> feat: output mediaType from get-image-archs

- templates/advisory.yaml.jinja
This will be an optional in the releaseNotes, but we want it to be set in the resulting advisory yaml always, defaulting to false.
> feat(RELEASE-1843): add skip_customer_notifications field in advisories

- utils/tests/test_apply_template.py
Forgot to do this when adding the new field in the template: https://github.com/konflux-ci/release-service-utils/pull/516
> chore(RELEASE-1843): add tests for skip_customer_notifications field

- templates/advisory.yaml.jinja
Until now, we used `>-` for multiline strings for some of the fields in the advisory jinja template. That means that we were removing most newlines from the input string. We shouldn't do that. We should pass the string that the user provided on input unmodified.
With `|-`, all newlines will be preserved.
> fix(RELEASE-1767): keep newlines in advisory fields

- utils/wait-for-internal-request
This commit modifies the wait-for-internal-request script to print out the pipelineRun in its loop. It will only be printed out if the IR is running or done. It is added to the existing "running" and "succeeded" prints.
> feat(RELEASE-376): print pipelineRun in wait-for-internal-request
