konflux-ci/release-service-utils

Dockerfile

fix: clone repo in dockerfile to /home

---

Dockerfile

feat: use python 3.9 in release-utils image

---

Dockerfile
pyxis/create_container_image

This commit adds the create_container_image script to PATH

feat(HACBS-1261): add pyxis/create_container_image to PATH

---

get-kubeconfig-from-service-account.sh

This is a very rough script that creates a *KUBECONFIG* given a service account that gets created in infra-deployments

Add get-kubeconfig-from-service-account

---

setup-quay-push-secret.sh

The script can be more permissible when detecting SPI phases. We have converted Errors to be warnings

fix(HACBS-1575): change errors to warnings

---

setup-quay-push-secret.sh

See https://github.com/redhat-appstudio/service-provider-integration-operator/blob/main/docs/USER.md#overriding-default-binding-lifetime

fix(hacbs-1715): set an infinite lifetime for SA

---

.github/workflows/python.yaml

I would've rather have the action run on our image and not have to install `requests`, but that doesn't seem too easy to do with github actions

feat(HACBS-1803): add pytest pr check

---

setup-quay-push-secret.sh

- take advantage of newly enabled feature in SPI that allows SPITokens to be created using kubectl
- this allows SPI to work across shared workspaces.
- the script has also be updated to re-use a ServiceAccount if one exists this will enable teams to add additional secrets to a ServiceAccount

fix(hacbs-2007): add support for SPITokens and shared workspaces

---

utils/merge-json

Compact json is easier to work with in tekton tasks.

refactor: use compact json

---

Dockerfile

Update Dockerfile to include what's missing from the bundles Dockerfile.

feat(HACBS-2425): add jq and krb5-workstation to dockerfile

---

utils/update-paths

This PR adds the update-paths script to enable updating
yq expression in fileUpdates paths strings with the result
of these expressions

feat(HACBS-2227): snapshot data model can be used in update expressions

---

pyxis/create_container_image.py
pyxis/test_create_container_image.py

Based on the mediaType returned by `skopeo inspect --raw`, the create_container_image will determine if the image is single arch or multi arch and based on that
it will populate either manifest_schema2_digest
or manifest_list_digest in the embedded
ContainerImageRepo object when creating a new
image in Pyxis.
This also removes the docker_image_digest and
image_id fields when creating the image. This is to align with metaxor which does not populate these either.
Note that currently we do not really support multi arch images in RHTAP and other changes will likely be needed to fully support them.
Once this is merged, we will update the create-pyxis-image tekton task to supply the new parameter when calling this script: https://github.com/redhat-appstudio/release-service-bundles/pull/195

fix(RHTAPBUGS-756): set digest in repo when creating an image in Pyxis

---

.github/workflows/build_and_push_image.yaml
.github/workflows/lint.yaml
.github/workflows/python.yaml

Adds the workflow file to run lint checks for new PRs
Also adds the CODEOWNERS file

fix(RHTAPBUGS-763): run lint checks for prs

---

Dockerfile

- updated due to Important CVE fix

fix(deps): update ubi8

---

pyxis/create_container_image.py
pyxis/test_create_container_image.py

If set to true, the registry and repository entries in the Pyxis Container Image object will be converted to use Red Hat's official registry. E.g. a mapped repository
of quay.io/redhat-pending/product---my-image will be converted to use registry registry.access.redhat.com and repository product/my-image.
Also, the image will be marked as published.
This will be used in the rh-push-to-registry-redhat-io pipeline.

feat(RHTAPREL-618): add rh-push option when creating pyxis image

---

Dockerfile

Needed for the create-github-release task in the release-service-catalog. To be added in this PR: https://github.com/redhat-appstudio/release-service-catalog/pull/281

chore: add gh CLI to image

---

.sonarcloud.properties

This commit Adds sonar cloud properties for better control.
Signed-off-by msawood@redhat.com
https://issues.redhat.com/browse/RHTAPREL-713

feat: Add sonar cloud properties

---

README.md

chore: retrigger

---

.tekton/release-service-utils-pull-request.yaml
.tekton/release-service-utils-push.yaml

chore: enable source builds

---

README.md

We need a new build and GitHub was degraded when we merged our last PR, so this is a small, essentially noop change to get us a new build

chore: small change to trigger build

---

templates/advisory.yaml.jinja

This will be populated when creating the advisory.

feat(RHTAPREL-799): add ship_date parameter to advisory template

---

Dockerfile
pyxis/test_upload_rpm_manifest.py
pyxis/upload_rpm_manifest
pyxis/upload_rpm_manifest.py
pyxis/upload_sbom.py
requirements.txt

This commit adds a utility to the pyxis directory for uploading RPM
Manifests via graphql queries.

feat(KFLUXBUGS-1115): add upload_rpm_manifest python util

---

utils/get-image-architectures

There's an example in the README at https://github.com/ralphbean/merlinite-poc

Support non-image OCI artifacts

---

utils/internal-request

This commit modifies the internal-request script to accept a serviceAccount option that will be added to the InternalRequest Spec if passed.

feat(RELEASE-1048): allow passing SA to IR

---

pyxis/create_container_image.py
pyxis/test_create_container_image.py

A new cli argument --dockerfile was added to be able to point to a Dockerfile to be included in the ContainerImage.parsed_data field when creating a new image.
I successfully tested this by running the script to create an image in stage Pyxis and when I read it back, it contained the Dockerfile contents as expected:
```json
{
...
"parsed_data": {
"architecture": "amd64",
"files": [
{
"content": "FROM registry.access.redhat.com/ubi9/ubi:9.4-1181\nRUN echo \"hello first build stage from ubi9\" >/hello.txt\n\nFROM registry.access.redhat.com/ubi8/nodejs-20@sha256:357b35e91e14580b9583498ffdd3b08eb1ede1b9676f7bf566f66fb14d7e3a92 \n\nCOPY --from=0 /hello.txt /hello-world.txt\n\n# Create and change to the app directory.\nWORKDIR /usr/src/app\n\n# Copy application dependency manifests to the …
```

feat(RELEASE-1033): add option to save Dockerfile to Pyxis

---

Dockerfile
developer-portal-wrapper/developer_portal_wrapper
developer-portal-wrapper/developer_portal_wrapper.py
developer-portal-wrapper/test_developer_portal_wrapper.py

- removed python code from Tekton task and placed as separate script with tests

feat(RELEASE-1108): new dev portal wrapper

---

developer-portal-wrapper/developer_portal_wrapper.py

- correct value used for shortUrl in dev portal

fix(RELEASE-1125): correct shortUrl for dev portal

---

Dockerfile
sbom/create_product_sbom
sbom/create_product_sbom.py
sbom/test_create_product_sbom.py

Add a python script to create product-level SBOMs in the `create-product-sbom` tekton task.

feat(ISV-5129): add script to create product-level SBOMs

---

sbom/create_product_sbom.py
sbom/test_create_product_sbom.py

The script used the wrong field for the data of images. This PR fixes that issue.

fix: use correct field for image data

---

Dockerfile

chore: update gitlab cli version

---

pyxis/create_container_image.py
pyxis/test_create_container_image.py

From the beginning, we would create a second
registry.access.redhat.com entry when releasing
to Red Hat registry. But it turns out we don't need two separate entries. The traditional SP pipeline
only creates one as well.
This is related to a previous change which implemented adding a new repository: https://github.com/konflux-ci/release-service-utils/pull/303
When I discussed that change with Ralph, he confirmed that the quay.io repository item is not needed, but we didn't want to make more changes than necessary, so it was kept. Let's remove it now.

fix: do not create duplicate repo for rh push

---

utils/internal-pipelinerun

fix(RELEASE-1354): path for internal pipelines

---

Dockerfile

Added pubtools-sign and pubtools-pyxis to Dockerfile as dependency to enable signing with pubtools-sign

feat(CLOUDDST-25757): Added pubtools-sign and pubtools-pyxis deps

---

pyxis/create_container_image.py
pyxis/upload_rpm_data.py

This commit updates the files that interact with pyxis to mention that any changes to how they function should be run by the pyxis team on slack.

docs: add note to pyxis files to run changes by pyxis team

---

.tekton/release-service-utils-pull-request.yaml
.tekton/release-service-utils-push.yaml

Starting from 1st of April 2025, the Shell Check (sast-shell-check) and Unicode (sast-unicode-check)
will become required tasks

chore: add required sast tasks in pipelineRun

---

pyxis/cleanup_tags.py
pyxis/test_cleanup_tags.py

this PR fixes the case when the image has multiple repositories and ends up not cleaning tags of all
of them.
Signed-off-by: Leandro Mendes <lmendes@redhat.com>

fix(RELEASE-1491): cleanup_tags supports multiple repos

---

utils/apply_template.py
utils/test_apply_template.py

- in some situations, users might want some control over how
certain release notes fields are generated based on advisory
values.
- an example would be a user placing this in their RP/RPA
``` 
spec:
data:
releaseNotes:
synopsis: >-
"{% if advisory.spec.type == 'RHEA' %}Enhancement
{% endif %}"
```
- this change uses a 2 step rendering process. The 1st one renders
the initial template. The 2nd rendering pass renders any template
partials from the data model that may have been supplied by the
RP/RPAs or via a Collector.
- this change also adds proper logging.

feat: support jinja expressions in data

---

utils/translate-delivery-repo

There's a new registry coming up PROJQUAY-8882.

feat(RHEL-50244): add rh-flatpaks repo translations

---

Dockerfile

Needed by push-oot-kmods task in release-service-catalog. Task will be added in this PR:
https://github.com/konflux-ci/release-service-catalog/pull/1000#discussion_r2143373753

chore(KFLUXMIG-294): Add git-lfs to image

---

sbom/sbomlib.py
sbom/test_sbomlib.py
sbom/update_component_sbom.py

Add a semaphore to make_snapshot to limit concurrency.
Also restructured the logging a little bit.

feat: introduce concurrency limit to make_snapshot

---

utils/apply_template.py
utils/tests/test_apply_template.py

- large datasets can produce argument too long error.
- we allow a data-file argument to get around that.

fix: new argument for data-file

---

Dockerfile

feat(RPRM-44): add pulp cli to image
